### ISSUE TITLE
Links truncated in the log

### ISSUE THREAD

**Issue by mestaritonttu** [kiwiirc/kiwibnc#114]
Long links like https://wiki.documentfoundation.org/Development/gerrit/SubmitPatch#Submitting_a_new_version will appear truncated in the text log as `https://wiki.documentfoundation.org/Development/gerrit/SubmitPatch#Submit_a_patch_for_review_with_ge...`

This is not very helpful.

**Comment by prawnsalad** [comment]
Hm there is no truncating of any kind in kiwibnc. Can you paste a raw log snippet?

**Comment by mestaritonttu** [comment]
Sorry for the noise, I must have copied a truncated link from the Kiwi web interface earlier :(
