### ISSUE TITLE
l_error Server error 

### ISSUE THREAD

**Issue by nagharshita16** [kiwiirc/kiwibnc#124]
When I run kiwibnc, then the error---- "l_error Server error 95421fe4-b6a4-4e8b-b3dc-f4f24285330d listen EADDRINUSE: address already in use 0.0.0.0:80"
is displayed in one of the messages.

**Comment by prawnsalad** [comment]
> EADDRINUSE

Means that port 80 is already in use by a different server on your system. Either change the port kiwibnc is listening on or stop your existing web server and re-try kiwibnc.
