### ISSUE TITLE
/msg *bnc help <command> gives the list of available commands

### ISSUE THREAD

**Issue by Mikaela** [kiwiirc/kiwibnc#136]
I think `/msg *bnc help <command>` should provide the syntax and explanation on how to use the command or what does it do. In this case I am wondering how to tell the bouncer my NickServ password and whether `setpass` changes my bouncer password or is Matrix style `!setpass` which stores my password so I won't get logged out.

<html>
<body>

2021 13:23:02 | <*bnc> | Here are the supported commands:
-- | -- | --
2021 13:23:02 | <*bnc> | ADDNETWORK ADDTOKEN ADDUSER ATTACH CHANGENETWORK CHANGETOKEN CONNECT DELNETWORK DELTOKEN DISCONNECT HELLO HELP HEY HI HOLA KILL LISTCLIENTS LISTNETWORKS LISTTOKENS OLA RELOAD SETPASS STATUS
2021 13:23:25 | <Mikaela> | help setpass
2021 13:23:25 | <*bnc> | Here are the supported commands:
2021 13:23:25 | <*bnc> | ADDNETWORK ADDTOKEN ADDUSER ATTACH CHANGENETWORK CHANGETOKEN CONNECT DELNETWORK DELTOKEN DISCONNECT HELLO HELP HEY HI HOLA KILL LISTCLIENTS LISTNETWORKS LISTTOKENS OLA RELOAD SETPASS STATUS

</body>
</html>

**Comment by prawnsalad** [comment]
Sorry, I'd forgot to come back to this issue. This was added in master here https://github.com/kiwiirc/kiwibnc/commit/cfd7bbe44227eec95542a2d33d71c6ec21019ca4
