### ISSUE TITLE
Bump knex to >= 1.0.1 and adapt src/libs/database.js so we can drop sqlite3 dependency

### ISSUE THREAD

**Issue by mestaritonttu** [kiwiirc/kiwibnc#142]
knex supports better-sqlite3 starting from 1.0.1!

The currently used sqlite3 is bad, because it uses node-gyp version 3.x, which requires Python 2. In other words, KiwiBNC is currently in dependency hell :)

Here are the relevant docs for knex:
https://github.com/knex/documentation/blob/8564d89988d553edd808211954fac0b784d63e66/sections/installation.js#L103-L130

Code modifications should be made to src/libs/database.js

**Comment by ChristopherTheBoss** [comment]
PLz fix <3 I am quasi zoomer trying to get into IRC, Kiwi seems friendly but idk about dependency hell
