### ISSUE TITLE
"Load previous messages" element sometimes disappears after first click

### ISSUE THREAD

**Issue by mestaritonttu** [kiwiirc/kiwibnc#44]
The element
`<a class="u-link">Load previous messages</a>`
sometimes goes away after loading previous messages once. It is not always reproducable.
Let me know, if I can insert some logging code to help find out what happens.

**Comment by prawnsalad** [comment]
I've pushed to master a change that will ensure a message ID exists on incoming messages which should fix this for messages from this point forward - not for existing messages. If you could update your kiwibnc to git master when you get a chance and see how it goes for a week, hopefully it should be resolved.

**Comment by mestaritonttu** [comment]
Message loading now seems to be working robustly, thanks!

**Comment by mestaritonttu** [comment]
I celebrated too soon. Now I am getting this again consistently.

**Comment by prawnsalad** [comment]
There was some fiddly changes to the messagelist recently that cause a regression in master, but luckily we caught it here https://github.com/kiwiirc/kiwiirc/pull/1376
