### ISSUE TITLE
Exposing the websocket via TLS

### ISSUE THREAD

**Issue by kalikiana** [kiwiirc/kiwibnc#49]
I setup KiwiBNC and naturally put it behind an nginx reverse proxy with a Let's Encrypt certificate. Unfortunately login is impossible in Chrome because the websocket would still go through `ws://` rather than `wss://`.

**Comment by slawus** [comment]
Same issue for me, it would be great if WebGUI could simply detect either its running over https or https and use wss / ws accordingly.

**Comment by prawnsalad** [comment]
@kalikiana @slawus, could you both:
1. Update your kiwibnc
2. Delete your kiwibnc webroot folder (assuming you havent changed anything in there)
3. Restart your kiwibnc

It will re-download the latest kiwiirc client version which now auto detects http/https

**Comment by prawnsalad** [comment]
This has been fixed in master. Updating your local kiwiirc client will get it working as expected.
