### ISSUE TITLE
Ignoring CTCP communication means not logging emotes

### ISSUE THREAD

**Issue by mestaritonttu** [kiwiirc/kiwibnc#51]
The mystery with missing messages in logs is solved: all /me emotes are dropped because CTCP requests/responses are ignored in src/worker/messagestores/flatfile.js and src/worker/messagestores/sqlite.js

**Comment by prawnsalad** [comment]
Good find! Now fixed in master :)

**Comment by mestaritonttu** [comment]
I tested and emotes are still not logged.

**Comment by prawnsalad** [comment]
Oops, looks like it was checking in the wrong place. I've just tested it in latest master and it's now storing ACTION emotes.
