### ISSUE TITLE
Text emoji 1st character trimmed if begins with a colon. 

### ISSUE THREAD

**Issue by TheBeerbarian** [kiwiirc/kiwibnc#8]
KiwiClient with direct connection.
![image](https://user-images.githubusercontent.com/24723440/57170418-00750080-6dca-11e9-9937-ce0ed082dea7.png)

KiwiClient with kiwiibnc connection.
![image](https://user-images.githubusercontent.com/24723440/57170424-0965d200-6dca-11e9-85cd-e478aae56462.png)

**Comment by DanielOaks** [comment]
Hmm, that looks pretty dodgy yeah. Any chance you can tell me whether this is just a regular message, a `/me` message, the realname, or somewhere else? I'll investigate and see what could be causing this, thanks for the report!

**Comment by TheBeerbarian** [comment]
Regular message to channel.

**Comment by DanielOaks** [comment]
Oh I see, can repro this. Yeah we're being a bit dodgy with how we interpret incoming lines it looks like, thanks.

**Comment by DanielOaks** [comment]
https://github.com/kiwiirc/irc-framework/pull/205 should resolve this, thanks for bringing up the issue!
