### ISSUE TITLE
Channel user list goes out of sync

### ISSUE THREAD

**Issue by mestaritonttu** [kiwiirc/kiwibnc#90]
Upgraded to the latest version a few days ago, removed connections.db. Now I still see user lists going out of sync, not displaying people that are present.

**Comment by prawnsalad** [comment]
@mestaritonttu with the ^ commit you should just need to update kiwibnc and refresh your kiwi page. If you try that and compare the user counts in the channels you saw that were out of sync then that will tell us if it's the fix we needed.

**Comment by mestaritonttu** [comment]
Thanks, seems OK now!
